### ISSUE TITLE
The search with and without diacritics doesn't work as expected (see PSE08)

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/Inscription-Search-Engine#1]
Users should be enable to include or exclude **diacritics** in their queries (default: exclude). By diacritics we mean:
- parentheses and brackets used in modern editions, especially those adopted by the [Leiden convention](https://en.wikipedia.org/wiki/Leiden_Conventions)
- Ancient Greek accents and breathing marks

This means that a query with the string "consul" should be able to retrieve also the string "co(n)s(ul)", while a query with the string "Αυρηλιος" should retrieve also "Αὐρήλιος" by default. This unless the user deliberately chooses to search for the abbreviated form "co(n)s(ul)" only.

**Comment by cprando** [comment]
This functionality is still under development.

**Comment by cprando** [comment]
Implemented

**Comment by francescomambrini** [comment]
It works very well in the Basic Search!
However, it doesn't in the Advanced Search (Text field): e.g., a search with "f(ecit)" gives 99631 results in the Basic and 609423 in the Advanced Search.

**Comment by francescomambrini** [comment]
I have some problems with the basic search as well. Why if I search for "filia" (should capture both with and without diacritics) I obtain 9782 results in the text category, and if I search for a common abbreviation "f(ilia)" I get more than 103091?
The query string "filia" should be more powerful and thus capture more results!

**Comment by cprando** [comment]
Advanced Search issue:
The reported behaviour is correct. Following a requirement that we received we implemented the Advanced Search in LIKE mode, while the Basic Search works by default in EXACT MATCH mode (you can search in LIKE mode by selecting "Include substrings"). This explains why you get more results searching for "f(ecit)" (without including substrings) in the Basic Search than in the Advanced Search.

**Comment by cprando** [comment]
Basic Search issue, here is the answer from Andrea M.:

Questa cosa credo sia collegata alla configurazione del tokenizer in Solr.
Al momento, quando si cerca f(ilia)
solr al suo interno decompone e cerca per "f" "ilia" ed "f(ilia)"
f è una sola lettera quindi fa match un po' dappertutto.

Questo comportamento lo si può configurare.
Vedo di spenderci un po' di tempo quando torno libero.
Cerchiamo di convergere ad una configurazione stabile perché ogni cambio significa dover indicizzare tutto di nuovo.

**Comment by andremann** [comment]
Solr should be fine now.

The WordDelimiterFilter has beed removed at query time so no decomposition/tokenization takes place on the string typed by the user.
However, this mechanism is still present at indexing time in order to produce smaller tokens and match broader queries. This is also functioning to make the query string "consul" match "consul" or any variant with diacritics such as "Co(n)s(ul)" or so.
I also provided to forcibly remove generated token with 1 or 2 letters in order to avoid the "f(ilia) effect".

As it is now configured, Solr has been tested against a benchmark of queries and seems to perform as expected.
@silviaorlandi 
[Benchmark](https://docs.google.com/document/d/1l7GCsrdqATqO1x6VYO2JPSz1_x4VCTTyrAD_x4Pcly8/edit?usp=sharing)

**Comment by andremann** [comment]
Also, some time ago i put in place a "folding filter" on Solr on both index and query time in order to perform normalization of "strange characters". 

[ICUFF Solr documentation](https://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.ICUFoldingFilterFactory)
[Unicode normalization forms](http://unicode.org/reports/tr15/)

**Comment by MaximilianHeiden** [comment]
Hi,
Take a look at  that coolest stuff ever! You've never seen something like that I swear! Here, check this out <http://yuri.305foreclosures.com/e8cie/6>

mlh.heiden

**Comment by MaximilianHeiden** [comment]
Hey, 

Have you seen that amazing things already? I swear you haven't! Check  it out  <http://alessandra.ejracing.net/e8vm/923>

Faithfully, mlh.heiden
